- name: Ensure vm.max_map_count is set
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: Ensure project directory exists
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Create .env file
  template:
    src: env.j2
    dest: "{{ project_dir }}/.env"
    mode: '0644'

- name: Deploy docker-compose.yml
  copy:
    src: docker-compose.yaml
    dest: "{{ project_dir }}/docker-compose.yml"

- name: Start Elasticsearch and Kibana with Docker Compose
  community.docker.docker_compose_v2:
   project_src: "{{ project_dir }}"
   state: present
