services:
  mongo:
    image: mongo:${IMAGE_VERSION}
    container_name: mongodb
    restart: ${RESTART_POLICY}
    ports:
      - "${MONGO_PORT}:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db 
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local