#SPDX-License-Identifier: MIT-0
---
- name: Ensure project directory exists
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Create .env file
  template:
    src: env.j2
    dest: "{{ project_dir }}/.env"
    mode: '0644'
  register: env

- name: Deploy docker-compose.yml
  copy:
    src: docker-compose.yaml
    dest: "{{ project_dir }}/docker-compose.yml"
  when: env is not failed

- name: Start Redis with Docker Compose
  community.docker.docker_compose_v2:
   project_src: "{{ project_dir }}"
   state: present